New demo: service-spawner
kiali/demos pull request #21
Opened 2021-01-29 12:36 UTC by jotak

2021-01-29 13:03 UTC, jmazzitelli requested changes

2021-01-29 13:03 UTC, jmazzitelli commented on service-spawner/gentpl.sh
> +#!/usr/bin/env bash
What does "gentpl" stand for? Can we rename this to something more human-readable/understandable? It isn't a linux utility, so we are free to use more than 6 letters in a command name :) How about "generate-circular-services.sh" or something descriptive like that?

2021-01-29 14:57 UTC, jotak commented on service-spawner/gentpl.sh
> +#!/usr/bin/env bash
I don't like very long names, how about a compromise : gen-services.sh ? :-)

2021-01-29 15:08 UTC, jmazzitelli approved these changes
lgtm

2021-02-01 08:09 UTC, merged

2021-02-01 08:09 UTC, lucasponce commented
Thanks @jotak !