Music store demo
kiali/demos pull request #32
Opened 2021-06-17 19:30 UTC by leandroberetta

Music store demo is a walk-trough to see how to configure traffic management rules in VirtualServices when these rules need to be applied to both internal and external traffic.

2021-06-17 19:40 UTC, jmazzitelli requested changes

2021-06-17 19:40 UTC, jmazzitelli commented on music-store/README.adoc
> +echo "$(minikube ip) backend.music.store" | sudo tee -a /etc/hosts
Because you are asking people to edit their DNS entries directly on their local machine, I would put a big warning message here or something that shouts loudly in order to indicate this part requires root access and will modify their DNS entries that affects their local machine.

Also, at the end of this README, because you are touching the host machine's config, you should have a "Cleanup" section and tell them to go into `/etc/hosts` and remove those entries.

2021-06-29 23:27 UTC, leandroberetta commented on music-store/README.adoc
> +echo "$(minikube ip) backend.music.store" | sudo tee -a /etc/hosts
Hi @jmazzitelli, thanks for the comment, I will try to remove this requirement if possible, but I need to do some testing, I'll be back!.

2021-07-01 13:44 UTC, leandroberetta commented on music-store/README.adoc
> +echo "$(minikube ip) backend.music.store" | sudo tee -a /etc/hosts
@jmazzitelli I removed the need of toucing the /etc/hosts!.

2021-07-01 15:13 UTC, jmazzitelli requested changes
I haven't run this demo yet, but while attempting to install the yaml, there are errors due to the way `echo` is being used in the commands (it fails for me, I'm on RHEL using bash, but I suspect this will fail on all Linux machines). Use cat + here-docs to properly apply the yaml which should be portable.

2021-07-01 15:13 UTC, jmazzitelli commented on music-store/README.adoc
> +  image: quay.io/leandroberetta/mimik-operator-index:v0.0.1" | kubectl apply -f -
This command does not work. It results in:

```
$ echo "apiVersion: operators.coreos.com/v1alpha1
> kind: CatalogSource
> metadata:
>   name: mimik-catalog
>   namespace: olm
> spec:
>   sourceType: grpc
>   image: quay.io/leandroberetta/mimik-operator-index:v0.0.1" | kubectl apply -f -
error: error validating "STDIN": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false
```

You should use cat with a [here-doc](https://tldp.org/LDP/abs/html/here-docs.html):

```suggestion
cat <<EOM | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: mimik-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/leandroberetta/mimik-operator-index:v0.0.1
EOM
```

2021-07-01 15:13 UTC, jmazzitelli commented on music-store/README.adoc
> +  sourceNamespace: olm" | kubectl apply -f -
As above, use cat + here-doc:

```suggestion
cat <<EOM | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mimik-subscription
  namespace: operators 
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: mimik-operator
  source: mimik-catalog
  sourceNamespace: olm
EOM
```

2021-07-01 15:13 UTC, jmazzitelli commented on music-store/README.adoc
> +      connections: []" | kubectl apply -f -
again, use here-doc to avoid errors:

```suggestion
cat <<EOM | kubectl apply -f -
apiVersion: mimik.veicot.io/v1alpha1
kind: Mimik
metadata:
  name: music-store-ui-v1
  namespace: music-store
spec:
  service: music-store-ui
  version: v1
  endpoints:
    - path: /
      method: GET
      connections:
        - service: music-store-backend
          port: 8080
          path: api
          method: GET
EOM

cat <<EOM | kubectl apply -f -
apiVersion: mimik.veicot.io/v1alpha1
kind: Mimik
metadata:
  name: music-store-backend-v1
  namespace: music-store
spec:
  service: music-store-backend
  version: v1
  endpoints:
    - path: /api
      method: GET
      connections: []
```

2021-07-01 15:13 UTC, jmazzitelli commented on music-store/README.adoc
> +              number: 8080" | kubectl apply -f -
use here-docs here, too

2021-07-01 15:13 UTC, jmazzitelli commented on music-store/README.adoc
> +              number: 8080" | kubectl apply -f -
use here-doc here, too

2021-07-01 15:13 UTC, jmazzitelli commented on music-store/README.adoc
> +              number: 8080" | kubectl apply -f -
use here-doc

2021-07-01 15:13 UTC, jmazzitelli commented on music-store/README.adoc
> +              number: 8080" | kubectl apply -f -
use here-doc

2021-07-01 15:27 UTC, leandroberetta commented on music-store/README.adoc
> +----
Thanks for your comments, strange about the echo command, i'm using Fedora and bash too.

Regarding olm, I thought it was broken on Minikube 1.19, but yes, i'm not specifying to use the latest version, I think it's better  to point to the yaml installation directly and avoid the addon.

2021-07-01 15:41 UTC, jmazzitelli commented on music-store/README.adoc
> +----
> Thanks for your comments, strange about the echo command, i'm using Fedora and bash too.

I don't know why I am getting that. I tried a similar (smaller) example and it worked. Strange. I would just switch to using here-docs, simply because that's how I've always seen examples and it makes it more readable (the first line of the yaml appears on the same line as the "echo" and you have to wrap the whole thing in quotes which isn't truly part of the yaml).

2021-07-02 21:36 UTC, jmazzitelli requested changes
I ran through this demo and it all worked. I do have some changes I recommend.

2021-07-02 21:36 UTC, jmazzitelli commented on music-store/README.adoc
> +In the VirtualService, the only gateway that is configured is the one that is related to the Ingress Gateway (external traffic getting into the mesh), so internal traffic is not being controlled by t
I would split up this run-on sentence. And correct the typo "an special value"  -- this should be "a special value":
```suggestion
In the VirtualService, the only gateway that is configured is the one that is related to the Ingress Gateway (external traffic getting into the mesh). This means internal traffic is not being controlled by this rule. To fix this situation, a special value "mesh" can be configured in the gateways list as follows:
```

2021-07-02 21:36 UTC, jmazzitelli commented on music-store/README.adoc
> +The previous command won't work and that is because as the error indicates, the "mesh" gateway is not allowed to be used when a wildcard host (*) is also configured, so to fix this situation, apply t
Split up the run-on sentence,  document the error message they should expect to see, and some other little things to reword this:

```suggestion
The previous command should fail with the following error: `admission webhook "validation.istio.io" denied the request: configuration is invalid: wildcard host * is not allowed for virtual services bound to the mesh gateway`. As the error indicates, the "mesh" gateway is not allowed to be used when a wildcard host (`"*"`) is also configured. To fix this situation, change the above command by replacing the wildcard with the two possible hosts that consumes the backend:
```

2021-07-02 21:36 UTC, jmazzitelli commented on music-store/README.adoc
> +Inpect the graph in Kiali again and observe that the rule is applying for both external and internal calls to the backend:
typo:
```suggestion
Inspect the graph in Kiali again and observe that the rule is applying for both external and internal calls to the backend:
```

2021-07-02 21:36 UTC, jmazzitelli commented on music-store/README.adoc
> +
When I was following the steps in this README, I was getting errors down below in the `for i in {1..100};` loop that curls the endpoint - that was because I didn't wait for the pods to start.

So I suggest adding this here:

```suggestion

Wait for the music-store pods to become available:
[source,bash]
----
kubectl wait -n music-store --for condition=available deployment/music-store-backend-v1
kubectl wait -n music-store --for condition=available deployment/music-store-ui-v1
----

```

2021-07-07 22:52 UTC, leandroberetta commented
@jmazzitelli thanks for the recommendations and refinements proposed, I pushed the improvements.

2021-07-08 14:02 UTC, jmazzitelli approved these changes
lgtm

2021-07-08 17:01 UTC, merged