Federated travels using OpenShift Service Mesh
kiali/demos pull request #35
Opened 2021-11-08 20:47 UTC by leandroberetta

This PR adds a new demo to deploy Travels but in a federation scenario using OSSM.

2021-11-10 12:07 UTC, lucasponce commented on federated-travels/README.md
> +oc apply -n east-mesh-system -f east/east-ossm.yaml
It would be nice to have same pattern for files, I like the copy&paste and to have an url with the raw, on this case I see that it requires to clone the repo first.

2021-11-10 12:23 UTC, lucasponce commented on federated-travels/README.md
> +oc apply -n east-travel-agency -f east-travel-agency.yaml
Here the file needs or an absolute url or a folder

2021-11-11 06:36 UTC, lucasponce requested changes
I've tested several times the example and it works really well.
Thanks @leandroberetta is very useful.

My only comment is that it would be nice to update all the commands in the readme to copy/paste them and avoid to clone a copy of the repo locally.

Otherwise pretty straightforward, it will help to jump into these use cases.

2021-11-11 10:55 UTC, leandroberetta commented
> I've tested several times the example and it works really well. Thanks @leandroberetta is very useful.
> 
> My only comment is that it would be nice to update all the commands in the readme to copy/paste them and avoid to clone a copy of the repo locally.
> 
> Otherwise pretty straightforward, it will help to jump into these use cases.

@lucasponce thanks for reviewing and for the feedback.

I updated the commands in the readme to avoid cloning.

2021-11-11 13:13 UTC, lucasponce approved these changes

2021-11-11 13:13 UTC, merged

2021-11-11 13:13 UTC, lucasponce commented
Thanks, the demo looks good, to use the latest changes it should be merged on master.

2021-11-11 15:49 UTC, prachiyadav commented
Approved.

Test case needs to be added