fix(error): add error handing logics
kiali/demos pull request #43
Opened 2021-12-25 03:06 UTC by Xunzhuo

2021-12-25 13:20 UTC, jmazzitelli requested changes

2021-12-25 13:20 UTC, jmazzitelli commented on topology-generator/pkg/service/service.go
> +func loadEndpoints(fileName string, endpoints *[]api.Endpoint) error {
why is there a duplicate function here? `func loadEndpoints(fileName string, endpoints *[]api.Endpoint) error` is already defined on l ine 23. I think you want to modify that function, not add a duplicate.

2021-12-25 13:22 UTC, Xunzhuo commented on topology-generator/pkg/service/service.go
> +func loadEndpoints(fileName string, endpoints *[]api.Endpoint) error {
Done, sorry I forgot to update codes

2021-12-29 06:53 UTC, Xunzhuo commented
cc @leandroberetta

2022-01-03 12:48 UTC, leandroberetta approved these changes
Looks good to me, thanks for adding more error handling logic.

2022-01-04 13:14 UTC, merged